"""Resolve knockout bracket slots from the app's own group standings.

The Bracket page historically filled knockout teams only from the
football-data.org feed, which assigns knockout-fixture teams late and
intermittently. But the app already computes group standings (with head-to-head
tiebreaks) from its own data, so the group-winner ("1A") and runner-up ("2B")
slots can be resolved directly -- no feed dependency, available the moment a
group's positions lock, and backed by the committed snapshot.

Third-place slots (e.g. "3ABCDF") are resolved too, via FIFA's fixed
best-eight-third allocation table (Annexe C, 495 combinations) committed at
``data/reference/third_place_allocation.csv`` and regenerated by
``scripts/fetch_third_place_allocation.py``.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

import pandas as pd


_ALLOCATION_CSV = Path(__file__).resolve().parents[1] / "data" / "reference" / "third_place_allocation.csv"

# The eight Round-of-32 matches where a group winner faces a best third-placed
# team. The allocation table assigns each a 3rd-place group per combination.
_THIRD_PLACE_MATCHES = (74, 77, 79, 80, 81, 82, 85, 87)


def all_slot_teams() -> dict[str, str]:
    """Every bracket slot we can resolve from our own data: 1X/2X from standings
    plus the eight 3rd-place slots from the FIFA allocation table."""
    return {**group_slot_teams(), **third_place_slot_teams()}


def group_slot_teams() -> dict[str, str]:
    """Map resolvable group slots to team names, e.g. ``{"1A": "USA", "2A": "Mexico"}``.

    Returns an empty mapping before any group games are played (no positions yet)
    or if the standings cannot be computed for any reason -- the bracket then just
    shows its placeholders, exactly as before.
    """
    groups = _group_standings()
    if groups.empty or "group_position" not in groups.columns:
        return {}

    slots: dict[str, str] = {}
    for _, row in groups.iterrows():
        position = row.get("group_position")
        if pd.isna(position):
            continue
        position = int(position)
        if position not in (1, 2):
            continue
        letter = str(row.get("group_name") or "").strip().upper()
        if len(letter) != 1 or not letter.isalpha():
            continue
        name = str(row.get("team") or "").strip()
        if name:
            slots[f"{position}{letter}"] = name
    return slots


def third_place_slot_teams() -> dict[str, str]:
    """Map the eight 3rd-place slot labels (e.g. ``"3ABCDF"``) to team names.

    Ranks the third-placed teams the same way the 3rd-Place Race tab does, takes
    the best eight, looks their group combination up in the FIFA allocation table,
    and slots each into the match its group is assigned to. Returns an empty
    mapping until eight third-placed teams exist and the combination is known.
    """
    ranking = _third_place_ranking()
    if ranking is None or len(ranking) < 8:
        return {}
    top_eight = ranking.iloc[:8]
    group_to_team = {
        str(row.get("group_name") or "").strip().upper(): str(row.get("team") or "").strip()
        for _, row in top_eight.iterrows()
    }
    groups = [g for g in group_to_team if len(g) == 1 and g.isalpha()]
    if len(groups) != 8:
        return {}
    allocation = _allocation_table().get("".join(sorted(groups)))
    if not allocation:
        return {}

    labels = _third_slot_labels()
    slots: dict[str, str] = {}
    for number in _THIRD_PLACE_MATCHES:
        team = group_to_team.get(allocation.get(number, ""))
        if team:
            slots[labels[number]] = team
    return slots


def _group_standings() -> pd.DataFrame:
    # Lazy import: groups.py pulls in Streamlit/page machinery, and keeping the
    # import inside the call keeps this module importable in plain tests.
    try:
        from src.pages.groups import _groups_with_standings

        return _groups_with_standings()
    except Exception:
        return pd.DataFrame()


def _third_place_ranking() -> pd.DataFrame | None:
    try:
        from src.pages.groups import _groups_with_standings, _third_place_table

        return _third_place_table(_groups_with_standings())
    except Exception:
        return None


def _third_slot_labels() -> dict[int, str]:
    from src.pages.bracket_data import MATCHES

    return {
        number: next(slot for slot in MATCHES[number]["slots"] if slot.startswith("3"))
        for number in _THIRD_PLACE_MATCHES
    }


@lru_cache(maxsize=1)
def _allocation_table() -> dict[str, dict[int, str]]:
    """{"ABCDEFGH": {74: "C", 77: "F", ...}} from the committed allocation CSV."""
    if not _ALLOCATION_CSV.exists():
        return {}
    frame = pd.read_csv(_ALLOCATION_CSV)
    table: dict[str, dict[int, str]] = {}
    for _, row in frame.iterrows():
        key = str(row["qualifying_groups"]).strip().upper()
        table[key] = {number: str(row[f"m{number}"]).strip().upper() for number in _THIRD_PLACE_MATCHES}
    return table
