from __future__ import annotations


MATCH_CITY_REFERENCE = [
    (1, "Group A", "Mexico vs South Africa", "Mexico City"),
    (2, "Group A", "Korea Republic vs Czechia", "Guadalajara"),
    (3, "Group B", "Canada vs Bosnia and Herzegovina", "Toronto"),
    (4, "Group D", "United States vs Paraguay", "Los Angeles"),
    (5, "Group C", "Haiti vs Scotland", "Boston"),
    (6, "Group D", "Australia vs Turkiye", "Vancouver"),
    (7, "Group C", "Brazil vs Morocco", "New York New Jersey"),
    (8, "Group B", "Qatar vs Switzerland", "San Francisco Bay Area"),
    (9, "Group E", "Cote d'Ivoire vs Ecuador", "Philadelphia"),
    (10, "Group E", "Germany vs Curacao", "Houston"),
    (11, "Group F", "Netherlands vs Japan", "Dallas"),
    (12, "Group F", "Sweden vs Tunisia", "Monterrey"),
    (13, "Group H", "Saudi Arabia vs Uruguay", "Miami"),
    (14, "Group H", "Spain vs Cabo Verde", "Atlanta"),
    (15, "Group G", "IR Iran vs New Zealand", "Los Angeles"),
    (16, "Group G", "Belgium vs Egypt", "Seattle"),
    (17, "Group I", "France vs Senegal", "New York New Jersey"),
    (18, "Group I", "Iraq vs Norway", "Boston"),
    (19, "Group J", "Argentina vs Algeria", "Kansas City"),
    (20, "Group J", "Austria vs Jordan", "San Francisco Bay Area"),
    (21, "Group L", "Ghana vs Panama", "Toronto"),
    (22, "Group L", "England vs Croatia", "Dallas"),
    (23, "Group K", "Portugal vs Congo DR", "Houston"),
    (24, "Group K", "Uzbekistan vs Colombia", "Mexico City"),
    (25, "Group A", "Czechia vs South Africa", "Atlanta"),
    (26, "Group B", "Switzerland vs Bosnia and Herzegovina", "Los Angeles"),
    (27, "Group B", "Canada vs Qatar", "Vancouver"),
    (28, "Group A", "Mexico vs Korea Republic", "Guadalajara"),
    (29, "Group C", "Brazil vs Haiti", "Philadelphia"),
    (30, "Group C", "Scotland vs Morocco", "Boston"),
    (31, "Group D", "Turkiye vs Paraguay", "San Francisco Bay Area"),
    (32, "Group D", "United States vs Australia", "Seattle"),
    (33, "Group E", "Germany vs Cote d'Ivoire", "Toronto"),
    (34, "Group E", "Ecuador vs Curacao", "Kansas City"),
    (35, "Group F", "Netherlands vs Sweden", "Houston"),
    (36, "Group F", "Tunisia vs Japan", "Monterrey"),
    (37, "Group H", "Uruguay vs Cabo Verde", "Miami"),
    (38, "Group H", "Spain vs Saudi Arabia", "Atlanta"),
    (39, "Group G", "Belgium vs IR Iran", "Los Angeles"),
    (40, "Group G", "New Zealand vs Egypt", "Vancouver"),
    (41, "Group I", "Norway vs Senegal", "New York New Jersey"),
    (42, "Group I", "France vs Iraq", "Philadelphia"),
    (43, "Group J", "Argentina vs Austria", "Dallas"),
    (44, "Group J", "Jordan vs Algeria", "San Francisco Bay Area"),
    (45, "Group L", "England vs Ghana", "Boston"),
    (46, "Group L", "Panama vs Croatia", "Toronto"),
    (47, "Group K", "Portugal vs Uzbekistan", "Houston"),
    (48, "Group K", "Colombia vs Congo DR", "Guadalajara"),
    (49, "Group C", "Scotland vs Brazil", "Miami"),
    (50, "Group C", "Morocco vs Haiti", "Atlanta"),
    (51, "Group B", "Switzerland vs Canada", "Vancouver"),
    (52, "Group B", "Bosnia and Herzegovina vs Qatar", "Seattle"),
    (53, "Group A", "Czechia vs Mexico", "Mexico City"),
    (54, "Group A", "South Africa vs Korea Republic", "Monterrey"),
    (55, "Group E", "Curacao vs Cote d'Ivoire", "Philadelphia"),
    (56, "Group E", "Ecuador vs Germany", "New York New Jersey"),
    (57, "Group F", "Japan vs Sweden", "Dallas"),
    (58, "Group F", "Tunisia vs Netherlands", "Kansas City"),
    (59, "Group D", "Turkiye vs United States", "Los Angeles"),
    (60, "Group D", "Paraguay vs Australia", "San Francisco Bay Area"),
    (61, "Group I", "Norway vs France", "Boston"),
    (62, "Group I", "Senegal vs Iraq", "Toronto"),
    (63, "Group G", "Egypt vs IR Iran", "Seattle"),
    (64, "Group G", "New Zealand vs Belgium", "Vancouver"),
    (65, "Group H", "Cabo Verde vs Saudi Arabia", "Houston"),
    (66, "Group H", "Uruguay vs Spain", "Guadalajara"),
    (67, "Group L", "Panama vs England", "New York New Jersey"),
    (68, "Group L", "Croatia vs Ghana", "Philadelphia"),
    (69, "Group J", "Algeria vs Austria", "Kansas City"),
    (70, "Group J", "Jordan vs Argentina", "Dallas"),
    (71, "Group K", "Colombia vs Portugal", "Dallas"),
    (72, "Group K", "Congo DR vs Uzbekistan", "Atlanta"),
    (73, "Round of 32", "2A vs 2B", "Los Angeles"),
    (74, "Round of 32", "1E vs 3ABCDF", "Boston"),
    (75, "Round of 32", "1F vs 2C", "Monterrey"),
    (76, "Round of 32", "1C vs 2F", "Houston"),
    (77, "Round of 32", "1I vs 3CDFGH", "New York New Jersey"),
    (78, "Round of 32", "2E vs 2I", "Dallas"),
    (79, "Round of 32", "1A vs 3CEFHI", "Mexico City"),
    (80, "Round of 32", "1L vs 3EHIJK", "Atlanta"),
    (81, "Round of 32", "1D vs 3BEFIJ", "San Francisco Bay Area"),
    (82, "Round of 32", "1G vs 3AEHIJ", "Seattle"),
    (83, "Round of 32", "2K vs 2L", "Toronto"),
    (84, "Round of 32", "1H vs 2J", "Los Angeles"),
    (85, "Round of 32", "1B vs 3EFGIJ", "Vancouver"),
    (86, "Round of 32", "1J vs 2H", "Miami"),
    (87, "Round of 32", "1K vs 3DEIJL", "Kansas City"),
    (88, "Round of 32", "2D vs 2G", "Dallas"),
    (89, "Round of 16", "Winner M74 vs Winner M77", "Philadelphia"),
    (90, "Round of 16", "Winner M73 vs Winner M75", "Houston"),
    (91, "Round of 16", "Winner M76 vs Winner M78", "New York New Jersey"),
    (92, "Round of 16", "Winner M79 vs Winner M80", "Mexico City"),
    (93, "Round of 16", "Winner M83 vs Winner M84", "Dallas"),
    (94, "Round of 16", "Winner M81 vs Winner M82", "Seattle"),
    (95, "Round of 16", "Winner M86 vs Winner M88", "Atlanta"),
    (96, "Round of 16", "Winner M85 vs Winner M87", "Vancouver"),
    (97, "Quarter-final", "Winner M89 vs Winner M90", "Boston"),
    (98, "Quarter-final", "Winner M93 vs Winner M94", "Los Angeles"),
    (99, "Quarter-final", "Winner M91 vs Winner M92", "Miami"),
    (100, "Quarter-final", "Winner M95 vs Winner M96", "Kansas City"),
    (101, "Semi-final", "Winner M97 vs Winner M98", "Dallas"),
    (102, "Semi-final", "Winner M99 vs Winner M100", "Atlanta"),
    (103, "Bronze final", "Loser M101 vs Loser M102", "Miami"),
    (104, "Final", "Winner M101 vs Winner M102", "New York New Jersey"),
]
